Mobile menu
teitonny/final-portfolio pull request #14
Opened 2022-10-18 09:57 UTC by teitonny

Added a mobile drop down menu to the project

2022-10-18 10:40 UTC, leonardodiasb requested changes
# INVALID ❌ ❌ ❌ 

Hi @, 👋

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌
 - The ESlint config is missing in the `linters.yml` file in the `.github/workflows` folder. Please update that file in order for the ESlint checks to run on the GitHub PR.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

----
_Invalid Code Review Request does not count into the code reviews limit._

2022-10-18 11:52 UTC, mirouhml requested changes
# REQUIRED CHANGES 🔴

Hi @teitonny , 

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media4.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif?cid=ecf05e47n6s5huda7qh40syoppcaspe9vx68ddmxerd08owm&rid=giphy.gif&ct=g)

## Highlights

- Great job setting up the correct linters ✔️
- Highly organized and clean code ✔️ 👨🏻‍💻
- Professional documentation ✔️
- Correct workflow ✔️
- Meaningful commit messages ✔️

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-18 11:52 UTC, mirouhml commented on styles.css
> +
Good job on completing the mobile menu it's working perfectly, there is only one thing to mention, it's about the design, please know that you should follow the Figma template design, your design is looking like this:
  ![image](https://user-images.githubusercontent.com/20567503/196421005-89e866fc-0b84-4351-afdc-c65bb32b2ee4.png)
  And the Figma design is looking like this:
  ![image](https://user-images.githubusercontent.com/20567503/196421172-41aef278-25a6-4a20-bc3d-1a5989582de8.png)
  From what I see the following should be changed:
  - [ ] The text is leaning to the right, it should be on the left according to the design, kindly change that.
  - [ ] The text isn't bold, and the size isn't the same as the one in Figma design, kindly adjust that as well.
  - [ ] The padding you put on top is a lot bigger than what is show on the Figma design, kindly adjust that as well.

2022-10-19 01:52 UTC, topeogunleye approved these changes
### Hi @teitonny, and Team

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good description :heavy_check_mark:
 
## [Optional] suggestions:
* [ ]  Please check my inline comments.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-19 01:52 UTC, topeogunleye commented on index.html
>      <header id="header">
- [ ] [OPTIONAL] I kindly suggest that you add `overflow: hidden` property to the body to prevent the user from accidentally scrolling away from where he previously was.
- [ ] I kindly suggest that you ensure that your overlay covers the entire page like it does for the Figma design

https://user-images.githubusercontent.com/52934128/196577823-880333a5-81f0-4427-91cb-07c1b141ed7b.mp4

2022-10-20 07:31 UTC, merged